CREATE TABLE IF NOT EXISTS users
(id serial PRIMARY KEY,
 num INTEGER NOT NULL UNIQUE,
 order_num INTEGER NOT NULL,
 price_us INTEGER NOT NULL,
 delivery_time DATE NOT NULL DEFAULT NOW(),
 price_rus INTEGER)

CREATE TABLE IF NOT EXISTS profile
CREATE TABLE profile
(id INTEGER PRIMARY KEY,
personal_uid INTEGER NOT NULL,
status BOOLEAN NOT NULL)

CREATE TABLE filters
(id INTEGER PRIMARY KEY, query_post VARCHAR(300), last_post VARCHAR(300), user_id INTEGER,
      CONSTRAINT pk_filters_sub FOREIGN KEY(user_id) REFERENCES subscribers (id))